/*
 * DigiValet PMS
 * This is DigiValet PMS application services for fetching room status, bill details, guest information, setting up wake up call etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * CheckinCheckoutDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-06-06T16:23:07.286Z")
public class CheckinCheckoutDetails   {
  @JsonProperty("guestDetails")
  private List<GuestDetails> guestDetails = null;

  @JsonProperty("operation")
  private String operation = null;

  @JsonProperty("feature")
  private String feature = null;

  public CheckinCheckoutDetails guestDetails(List<GuestDetails> guestDetails) {
    this.guestDetails = guestDetails;
    return this;
  }

  public CheckinCheckoutDetails addGuestDetailsItem(GuestDetails guestDetailsItem) {
    if (this.guestDetails == null) {
      this.guestDetails = new ArrayList<GuestDetails>();
    }
    this.guestDetails.add(guestDetailsItem);
    return this;
  }

  /**
   * Get guestDetails
   * @return guestDetails
   **/
  @JsonProperty("guestDetails")
  @ApiModelProperty(value = "")
  public List<GuestDetails> getGuestDetails() {
    return guestDetails;
  }

  public void setGuestDetails(List<GuestDetails> guestDetails) {
    this.guestDetails = guestDetails;
  }

  public CheckinCheckoutDetails operation(String operation) {
    this.operation = operation;
    return this;
  }

  /**
   * Get operation
   * @return operation
   **/
  @JsonProperty("operation")
  @ApiModelProperty(value = "")
  public String getOperation() {
    return operation;
  }

  public void setOperation(String operation) {
    this.operation = operation;
  }

  public CheckinCheckoutDetails feature(String feature) {
    this.feature = feature;
    return this;
  }

  /**
   * Get feature
   * @return feature
   **/
  @JsonProperty("feature")
  @ApiModelProperty(value = "")
  public String getFeature() {
    return feature;
  }

  public void setFeature(String feature) {
    this.feature = feature;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckinCheckoutDetails checkinCheckoutDetails = (CheckinCheckoutDetails) o;
    return Objects.equals(this.guestDetails, checkinCheckoutDetails.guestDetails) &&
        Objects.equals(this.operation, checkinCheckoutDetails.operation) &&
        Objects.equals(this.feature, checkinCheckoutDetails.feature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guestDetails, operation, feature);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckinCheckoutDetails {\n");
    
    sb.append("    guestDetails: ").append(toIndentedString(guestDetails)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    feature: ").append(toIndentedString(feature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

