/*
 * DigiValet PMS
 * This is DigiValet PMS application services for fetching room status, bill details, guest information, setting up wake up call etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * CheckoutRequestDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-08-29T09:41:32.663Z")
public class CheckoutRequestDetails   {
  @JsonProperty("guestId")
  private String guestId = null;

  @JsonProperty("roomNumber")
  private String roomNumber = null;

  @JsonProperty("hotelCode")
  private String hotelCode = null;
  

  @JsonProperty("targetDeviceId")
  private String targetDeviceId = null;
  

  public CheckoutRequestDetails targetDeviceId(String targetDeviceId) {
     this.targetDeviceId = targetDeviceId;
     return this;
   }

   /**
    * Get targetDeviceId
    * @return targetDeviceId
    **/
   @JsonProperty("targetDeviceId")
   @ApiModelProperty(value = "")
   public String getTargetDeviceId() {
     return targetDeviceId;
   }

   public void setTargetDeviceId(String targetDeviceId) {
     this.targetDeviceId = targetDeviceId;
   }
  
  public CheckoutRequestDetails guestId(String guestId) {
    this.guestId = guestId;
    return this;
  }

  /**
   * Get guestId
   * @return guestId
   **/
  @JsonProperty("guestId")
  @ApiModelProperty(value = "")
  public String getGuestId() {
    return guestId;
  }

  public void setGuestId(String guestId) {
    this.guestId = guestId;
  }

  public CheckoutRequestDetails roomNumber(String roomNumber) {
    this.roomNumber = roomNumber;
    return this;
  }

  /**
   * Get roomNumber
   * @return roomNumber
   **/
  @JsonProperty("roomNumber")
  @ApiModelProperty(value = "")
  public String getRoomNumber() {
    return roomNumber;
  }

  public void setRoomNumber(String roomNumber) {
    this.roomNumber = roomNumber;
  }

  public CheckoutRequestDetails hotelCode(String hotelCode) {
    this.hotelCode = hotelCode;
    return this;
  }

  /**
   * Get hotelCode
   * @return hotelCode
   **/
  @JsonProperty("hotelCode")
  @ApiModelProperty(value = "")
  public String getHotelCode() {
    return hotelCode;
  }

  public void setHotelCode(String hotelCode) {
    this.hotelCode = hotelCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutRequestDetails checkoutRequestDetails = (CheckoutRequestDetails) o;
    return Objects.equals(this.guestId, checkoutRequestDetails.guestId) &&
        Objects.equals(this.roomNumber, checkoutRequestDetails.roomNumber) &&
        Objects.equals(this.hotelCode, checkoutRequestDetails.hotelCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guestId, roomNumber, hotelCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutRequestDetails {\n");
    
    sb.append("    guestId: ").append(toIndentedString(guestId)).append("\n");
    sb.append("    roomNumber: ").append(toIndentedString(roomNumber)).append("\n");
    sb.append("    hotelCode: ").append(toIndentedString(hotelCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

