/*
 * DigiValet-IDA
 * This is DigiValet Server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * GuestDetailRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-01-21T13:21:56.464Z")
public class GuestDetailRequest   {
  @JsonProperty("request_params")
  private String requestParams = null;

  @JsonProperty("condition_params")
  private List<Items> conditionParams = null;

  @JsonProperty("conditional_operator")
  private String conditionalOperator = null;

  public GuestDetailRequest requestParams(String requestParams) {
    this.requestParams = requestParams;
    return this;
  }

  /**
   * Get requestParams
   * @return requestParams
   **/
  @JsonProperty("request_params")
  @ApiModelProperty(value = "")
  public String getRequestParams() {
    return requestParams;
  }

  public void setRequestParams(String requestParams) {
    this.requestParams = requestParams;
  }

  public GuestDetailRequest conditionParams(List<Items> conditionParams) {
    this.conditionParams = conditionParams;
    return this;
  }

  public GuestDetailRequest addConditionParamsItem(Items conditionParamsItem) {
    if (this.conditionParams == null) {
      this.conditionParams = new ArrayList<Items>();
    }
    this.conditionParams.add(conditionParamsItem);
    return this;
  }

  /**
   * Get conditionParams
   * @return conditionParams
   **/
  @JsonProperty("condition_params")
  @ApiModelProperty(value = "")
  public List<Items> getConditionParams() {
    return conditionParams;
  }

  public void setConditionParams(List<Items> conditionParams) {
    this.conditionParams = conditionParams;
  }

  public GuestDetailRequest conditionalOperator(String conditionalOperator) {
    this.conditionalOperator = conditionalOperator;
    return this;
  }

  /**
   * Get conditionalOperator
   * @return conditionalOperator
   **/
  @JsonProperty("conditional_operator")
  @ApiModelProperty(value = "")
  public String getConditionalOperator() {
    return conditionalOperator;
  }

  public void setConditionalOperator(String conditionalOperator) {
    this.conditionalOperator = conditionalOperator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuestDetailRequest guestDetailRequest = (GuestDetailRequest) o;
    return Objects.equals(this.requestParams, guestDetailRequest.requestParams) &&
        Objects.equals(this.conditionParams, guestDetailRequest.conditionParams) &&
        Objects.equals(this.conditionalOperator, guestDetailRequest.conditionalOperator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestParams, conditionParams, conditionalOperator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuestDetailRequest {\n");
    
    sb.append("    requestParams: ").append(toIndentedString(requestParams)).append("\n");
    sb.append("    conditionParams: ").append(toIndentedString(conditionParams)).append("\n");
    sb.append("    conditionalOperator: ").append(toIndentedString(conditionalOperator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

