/*
 * DigiValet Notification
 * This is DigiValet Notification services used to post guest preference to Digivalet
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.model;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;

/**
 * GuestPreferenceRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-12-21T11:32:48.219Z")
public class GuestPreferenceRequest   {
  @JsonProperty("details")
  private List<GuestPreferenceDetails> details = null;

  /**
   * Gets or Sets feature
   */
  public enum FeatureEnum {
    GUESTPREFERENCE("GuestPreference");

    private String value;

    FeatureEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FeatureEnum fromValue(String text) {
      for (FeatureEnum b : FeatureEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("feature")
  private FeatureEnum feature = null;

  /**
   * Gets or Sets operation
   */
  public enum OperationEnum {
    POSTPREFERENCE("PostPreference");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperationEnum fromValue(String text) {
      for (OperationEnum b : OperationEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("operation")
  private OperationEnum operation = null;

  public GuestPreferenceRequest details(List<GuestPreferenceDetails> details) {
    this.details = details;
    return this;
  }

  public GuestPreferenceRequest addDetailsItem(GuestPreferenceDetails detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<GuestPreferenceDetails>();
    }
    this.details.add(detailsItem);
    return this;
  }

  /**
   * Get details
   * @return details
   **/
  @JsonProperty("details")
  @ApiModelProperty(value = "")
  public List<GuestPreferenceDetails> getDetails() {
    return details;
  }

  public void setDetails(List<GuestPreferenceDetails> details) {
    this.details = details;
  }

  public GuestPreferenceRequest feature(FeatureEnum feature) {
    this.feature = feature;
    return this;
  }

  /**
   * Get feature
   * @return feature
   **/
  @JsonProperty("feature")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public FeatureEnum getFeature() {
    return feature;
  }

  public void setFeature(FeatureEnum feature) {
    this.feature = feature;
  }

  public GuestPreferenceRequest operation(OperationEnum operation) {
    this.operation = operation;
    return this;
  }

  /**
   * Get operation
   * @return operation
   **/
  @JsonProperty("operation")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public OperationEnum getOperation() {
    return operation;
  }

  public void setOperation(OperationEnum operation) {
    this.operation = operation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuestPreferenceRequest guestPreferenceRequest = (GuestPreferenceRequest) o;
    return Objects.equals(this.details, guestPreferenceRequest.details) &&
        Objects.equals(this.feature, guestPreferenceRequest.feature) &&
        Objects.equals(this.operation, guestPreferenceRequest.operation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, feature, operation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuestPreferenceRequest {\n");
    
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    feature: ").append(toIndentedString(feature)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

