/*
 * DigiValet Notification
 * This is DigiValet Notification services used to post guest preference to Digivalet
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.model;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * GuestPreferenceDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-12-21T11:32:48.219Z")
public class GuestPreferenceDetails   {
  @JsonProperty("PreferenceDetails")
  private List<PreferenceData> preferenceDetails = null;

  public GuestPreferenceDetails preferenceDetails(List<PreferenceData> preferenceDetails) {
    this.preferenceDetails = preferenceDetails;
    return this;
  }

  public GuestPreferenceDetails addPreferenceDetailsItem(PreferenceData preferenceDetailsItem) {
    if (this.preferenceDetails == null) {
      this.preferenceDetails = new ArrayList<PreferenceData>();
    }
    this.preferenceDetails.add(preferenceDetailsItem);
    return this;
  }

  /**
   * Get preferenceDetails
   * @return preferenceDetails
   **/
  @JsonProperty("PreferenceDetails")
  @ApiModelProperty(value = "")
  public List<PreferenceData> getPreferenceDetails() {
    return preferenceDetails;
  }

  public void setPreferenceDetails(List<PreferenceData> preferenceDetails) {
    this.preferenceDetails = preferenceDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuestPreferenceDetails guestPreferenceDetails = (GuestPreferenceDetails) o;
    return Objects.equals(this.preferenceDetails, guestPreferenceDetails.preferenceDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preferenceDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuestPreferenceDetails {\n");
    
    sb.append("    preferenceDetails: ").append(toIndentedString(preferenceDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

