/*
 * DigiValet PMS This is DigiValet PMS application services for fetching room
 * status, bill details, guest information, setting up wake up call etc.
 *
 * OpenAPI spec version: 1.0.0 Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */


package com.digivalet.pmsi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * GuestDetails
 */
@javax.annotation.Generated(
         value = "io.swagger.codegen.languages.JavaJerseyServerCodegen",
         date = "2017-11-03T08:52:10.265Z")
public class GuestDetails
{
   @JsonProperty("guestName")
   private String guestName = null;

   @JsonProperty("guestTitle")
   private String guestTitle = null;

   @JsonProperty("guestFirstName")
   private String guestFirstName = null;

   @JsonProperty("guestLastName")
   private String guestLastName = null;

   @JsonProperty("guestFullName")
   private String guestFullName = null;

   @JsonProperty("roomNumber")
   private String roomNumber = null;

   @JsonProperty("remoteCheckout")
   private Boolean remoteCheckout = null;

   @JsonProperty("safeFlag")
   private Boolean safeFlag = false;

   @JsonProperty("revisitFlag")
   private Boolean revisitFlag = null;

   @JsonProperty("tvRights")
   private String tvRights = null;

   @JsonProperty("isAdult")
   private String isAdult = null;

   @JsonProperty("videoRights")
   private String videoRights = null;

   @JsonProperty("vipStatus")
   private String vipStatus = null;

   @JsonProperty("alternateName")
   private String alternateName = null;

   @JsonProperty("incognitoName")
   private String incognitoName = null;

   @JsonProperty("arrivalDate")
   private String arrivalDate = null;

   @JsonProperty("departureDate")
   private String departureDate = null;

   @JsonProperty("guestLanguage")
   private String guestLanguage = null;

   @JsonProperty("guestId")
   private String guestId = null;

   @JsonProperty("reservationId")
   private String reservationId = null;

   @JsonProperty("emailId")
   private String emailId = null;

   @JsonProperty("phoneNumber")
   private String phoneNumber = null;

   @JsonProperty("groupCode")
   private String groupCode = null;

   @JsonProperty("uniqueId")
   private String uniqueId = null;

   @JsonProperty("guestType")
   private String guestType = null;

   @JsonProperty("welcomeMoodId")
   private String welcomeMoodId = "";

   @JsonProperty("fragrance")
   private String fragrance = "";

   @JsonProperty("temperature")
   private String temperature = "";


   @JsonProperty("fragrance")
   @ApiModelProperty(value = "")
   public String getFragrance()
   {
      return fragrance;
   }

   public GuestDetails fragrance(String fragrance)
   {
      this.fragrance = fragrance;
      return this;
   }

   public void setFragrance(String fragrance)
   {
      this.fragrance = fragrance;
   }

   @JsonProperty("temperature")
   @ApiModelProperty(value = "")
   public String getTemperature()
   {
      return temperature;
   }

   public void setTemperature(String temperature)
   {
      this.temperature = temperature;
   }

   public GuestDetails temperature(String temperature)
   {
      this.temperature = temperature;
      return this;
   }


   public GuestDetails guestName(String guestName)
   {
      this.guestName = guestName;
      return this;
   }

   /**
    * Get guestName
    * 
    * @return guestName
    **/
   @JsonProperty("guestName")
   @ApiModelProperty(value = "")
   public String getGuestName()
   {
      return guestName;
   }

   public void setGuestName(String guestName)
   {
      this.guestName = guestName;
   }

   public GuestDetails guestTitle(String guestTitle)
   {
      this.guestTitle = guestTitle;
      return this;
   }

   /**
    * Get guestTitle
    * 
    * @return guestTitle
    **/
   @JsonProperty("guestTitle")
   @ApiModelProperty(value = "")
   public String getGuestTitle()
   {
      return guestTitle;
   }

   public void setGuestTitle(String guestTitle)
   {
      this.guestTitle = guestTitle;
   }

   public GuestDetails guestFirstName(String guestFirstName)
   {
      this.guestFirstName = guestFirstName;
      return this;
   }

   /**
    * Get guestFirstName
    * 
    * @return guestFirstName
    **/
   @JsonProperty("guestFirstName")
   @ApiModelProperty(value = "")
   public String getGuestFirstName()
   {
      return guestFirstName;
   }

   public void setGuestFirstName(String guestFirstName)
   {
      this.guestFirstName = guestFirstName;
   }

   public GuestDetails guestLastName(String guestLastName)
   {
      this.guestLastName = guestLastName;
      return this;
   }

   /**
    * Get guestLastName
    * 
    * @return guestLastName
    **/
   @JsonProperty("guestLastName")
   @ApiModelProperty(value = "")
   public String getGuestLastName()
   {
      return guestLastName;
   }

   public void setGuestLastName(String guestLastName)
   {
      this.guestLastName = guestLastName;
   }

   public GuestDetails guestFullName(String guestFullName)
   {
      this.guestFullName = guestFullName;
      return this;
   }

   /**
    * Get guestFullName
    * 
    * @return guestFullName
    **/
   @JsonProperty("guestFullName")
   @ApiModelProperty(value = "")
   public String getGuestFullName()
   {
      return guestFullName;
   }

   public void setGuestFullName(String guestFullName)
   {
      this.guestFullName = guestFullName;
   }

   public GuestDetails roomNumber(String roomNumber)
   {
      this.roomNumber = roomNumber;
      return this;
   }

   /**
    * Get roomNumber
    * 
    * @return roomNumber
    **/
   @JsonProperty("roomNumber")
   @ApiModelProperty(value = "")
   public String getRoomNumber()
   {
      return roomNumber;
   }

   public void setRoomNumber(String roomNumber)
   {
      this.roomNumber = roomNumber;
   }

   public GuestDetails remoteCheckout(Boolean remoteCheckout)
   {
      this.remoteCheckout = remoteCheckout;
      return this;
   }

   /**
    * Get remoteCheckout
    * 
    * @return remoteCheckout
    **/
   @JsonProperty("remoteCheckout")
   @ApiModelProperty(value = "")
   public Boolean getRemoteCheckout()
   {
      return remoteCheckout;
   }

   public void setRemoteCheckout(Boolean remoteCheckout)
   {
      this.remoteCheckout = remoteCheckout;
   }

   public GuestDetails safeFlag(Boolean safeFlag)
   {
      this.safeFlag = safeFlag;
      return this;
   }

   /**
    * Get safeFlag
    * 
    * @return safeFlag
    **/
   @JsonProperty("safeFlag")
   @ApiModelProperty(value = "")
   public Boolean getSafeFlag()
   {
      return safeFlag;
   }

   public void setSafeFlag(Boolean safeFlag)
   {
      this.safeFlag = safeFlag;
   }

   public GuestDetails revisitFlag(Boolean revisitFlag)
   {
      this.revisitFlag = revisitFlag;
      return this;
   }

   /**
    * Get revisitFlag
    * 
    * @return revisitFlag
    **/
   @JsonProperty("revisitFlag")
   @ApiModelProperty(value = "")
   public Boolean getRevisitFlag()
   {
      return revisitFlag;
   }

   public void setRevisitFlag(Boolean revisitFlag)
   {
      this.revisitFlag = revisitFlag;
   }

   public GuestDetails tvRights(String tvRights)
   {
      this.tvRights = tvRights;
      return this;
   }

   /**
    * Get tvRights
    * 
    * @return tvRights
    **/
   @JsonProperty("tvRights")
   @ApiModelProperty(value = "")
   public String getTvRights()
   {
      return tvRights;
   }

   public void setTvRights(String tvRights)
   {
      this.tvRights = tvRights;
   }



   public GuestDetails isAdult(String isAdult)
   {
      this.isAdult = isAdult;
      return this;
   }

   /**
    * Get tvRights
    * 
    * @return tvRights
    **/
   @JsonProperty("isAdult")
   @ApiModelProperty(value = "")
   public String getIsAdult()
   {
      return isAdult;
   }

   public void setIsAdult(String isAdult)
   {
      this.isAdult = isAdult;
   }



   public GuestDetails videoRights(String videoRights)
   {
      this.videoRights = videoRights;
      return this;
   }

   /**
    * Get videoRights
    * 
    * @return videoRights
    **/
   @JsonProperty("videoRights")
   @ApiModelProperty(value = "")
   public String getVideoRights()
   {
      return videoRights;
   }

   public void setVideoRights(String videoRights)
   {
      this.videoRights = videoRights;
   }

   public GuestDetails vipStatus(String vipStatus)
   {
      this.vipStatus = vipStatus;
      return this;
   }

   /**
    * Get vipStatus
    * 
    * @return vipStatus
    **/
   @JsonProperty("vipStatus")
   @ApiModelProperty(value = "")
   public String getVipStatus()
   {
      return vipStatus;
   }

   public void setVipStatus(String vipStatus)
   {
      this.vipStatus = vipStatus;
   }

   public GuestDetails alternateName(String alternateName)
   {
      this.alternateName = alternateName;
      return this;
   }

   /**
    * Get alternateName
    * 
    * @return alternateName
    **/
   @JsonProperty("alternateName")
   @ApiModelProperty(value = "")
   public String getAlternateName()
   {
      return alternateName;
   }

   public void setAlternateName(String alternateName)
   {
      this.alternateName = alternateName;
   }

   public GuestDetails incognitoName(String incognitoName)
   {
      this.incognitoName = incognitoName;
      return this;
   }

   /**
    * Get incognitoName
    * 
    * @return incognitoName
    **/
   @JsonProperty("incognitoName")
   @ApiModelProperty(value = "")
   public String getIncognitoName()
   {
      return incognitoName;
   }

   public void setIncognitoName(String incognitoName)
   {
      this.incognitoName = incognitoName;
   }

   public GuestDetails arrivalDate(String arrivalDate)
   {
      this.arrivalDate = arrivalDate;
      return this;
   }

   /**
    * Get arrivalDate
    * 
    * @return arrivalDate
    **/
   @JsonProperty("arrivalDate")
   @ApiModelProperty(value = "")
   public String getArrivalDate()
   {
      return arrivalDate;
   }

   public void setArrivalDate(String arrivalDate)
   {
      this.arrivalDate = arrivalDate;
   }

   public GuestDetails departureDate(String departureDate)
   {
      this.departureDate = departureDate;
      return this;
   }

   /**
    * Get departureDate
    * 
    * @return departureDate
    **/
   @JsonProperty("departureDate")
   @ApiModelProperty(value = "")
   public String getDepartureDate()
   {
      return departureDate;
   }

   public void setDepartureDate(String departureDate)
   {
      this.departureDate = departureDate;
   }

   public GuestDetails guestLanguage(String guestLanguage)
   {
      this.guestLanguage = guestLanguage;
      return this;
   }

   /**
    * Get guestLanguage
    * 
    * @return guestLanguage
    **/
   @JsonProperty("guestLanguage")
   @ApiModelProperty(value = "")
   public String getGuestLanguage()
   {
      return guestLanguage;
   }

   public void setGuestLanguage(String guestLanguage)
   {
      this.guestLanguage = guestLanguage;
   }

   public GuestDetails guestId(String guestId)
   {
      this.guestId = guestId;
      return this;
   }

   /**
    * Get guestId
    * 
    * @return guestId
    **/
   @JsonProperty("guestId")
   @ApiModelProperty(value = "")
   public String getGuestId()
   {
      return guestId;
   }

   public void setGuestId(String guestId)
   {
      this.guestId = guestId;
   }

   public GuestDetails reservationId(String reservationId)
   {
      this.reservationId = reservationId;
      return this;
   }

   /**
    * Get reservationId
    * 
    * @return reservationId
    **/
   @JsonProperty("reservationId")
   @ApiModelProperty(value = "")
   public String getReservationId()
   {
      return reservationId;
   }

   public void setReservationId(String reservationId)
   {
      this.reservationId = reservationId;
   }

   public GuestDetails emailId(String emailId)
   {
      this.emailId = emailId;
      return this;
   }

   /**
    * Get emailId
    * 
    * @return emailId
    **/
   @JsonProperty("emailId")
   @ApiModelProperty(value = "")
   public String getEmailId()
   {
      return emailId;
   }

   public void setEmailId(String emailId)
   {
      this.emailId = emailId;
   }

   public GuestDetails phoneNumber(String phoneNumber)
   {
      this.phoneNumber = phoneNumber;
      return this;
   }

   /**
    * Get phoneNumber
    * 
    * @return phoneNumber
    **/
   @JsonProperty("phoneNumber")
   @ApiModelProperty(value = "")
   public String getPhoneNumber()
   {
      return phoneNumber;
   }

   public void setPhoneNumber(String phoneNumber)
   {
      this.phoneNumber = phoneNumber;
   }

   public GuestDetails groupCode(String groupCode)
   {
      this.groupCode = groupCode;
      return this;
   }

   /**
    * Get groupCode
    * 
    * @return groupCode
    **/
   @JsonProperty("groupCode")
   @ApiModelProperty(value = "")
   public String getGroupCode()
   {
      return groupCode;
   }

   public void setGroupCode(String groupCode)
   {
      this.groupCode = groupCode;
   }

   public GuestDetails uniqueId(String uniqueId)
   {
      this.uniqueId = uniqueId;
      return this;
   }

   /**
    * Get uniqueId
    * 
    * @return uniqueId
    **/
   @JsonProperty("uniqueId")
   @ApiModelProperty(value = "")
   public String getUniqueId()
   {
      return uniqueId;
   }

   public void setUniqueId(String uniqueId)
   {
      this.uniqueId = uniqueId;
   }

   public GuestDetails guestType(String guestType)
   {
      this.guestType = guestType;
      return this;
   }

   /**
    * Get guestType
    * 
    * @return guestType
    **/
   @JsonProperty("guestType")
   @ApiModelProperty(value = "")
   public String getGuestType()
   {
      return guestType;
   }

   public void setGuestType(String guestType)
   {
      this.guestType = guestType;
   }


   public GuestDetails welcomeMoodId(String welcomeMoodId)
   {
      this.welcomeMoodId = welcomeMoodId;
      return this;
   }

   /**
    * Get guestType
    * 
    * @return guestType
    **/
   @JsonProperty("welcomeMoodId")
   @ApiModelProperty(value = "")
   public String getWelcomeMoodId()
   {
      return welcomeMoodId;
   }

   public void setWelcomeMoodId(String welcomeMoodId)
   {
      this.welcomeMoodId = welcomeMoodId;
   }



   @Override
   public boolean equals(java.lang.Object o)
   {
      if (this == o)
      {
         return true;
      }
      if (o == null || getClass() != o.getClass())
      {
         return false;
      }
      GuestDetails guestDetails = (GuestDetails) o;
      return Objects.equals(this.guestName, guestDetails.guestName)
               && Objects.equals(this.guestTitle, guestDetails.guestTitle)
               && Objects.equals(this.guestFirstName,
                        guestDetails.guestFirstName)
               && Objects.equals(this.guestLastName, guestDetails.guestLastName)
               && Objects.equals(this.guestFullName, guestDetails.guestFullName)
               && Objects.equals(this.roomNumber, guestDetails.roomNumber)
               && Objects.equals(this.remoteCheckout,
                        guestDetails.remoteCheckout)
               && Objects.equals(this.safeFlag, guestDetails.safeFlag)
               && Objects.equals(this.revisitFlag, guestDetails.revisitFlag)
               && Objects.equals(this.tvRights, guestDetails.tvRights)
               && Objects.equals(this.videoRights, guestDetails.videoRights)
               && Objects.equals(this.vipStatus, guestDetails.vipStatus)
               && Objects.equals(this.alternateName, guestDetails.alternateName)
               && Objects.equals(this.incognitoName, guestDetails.incognitoName)
               && Objects.equals(this.arrivalDate, guestDetails.arrivalDate)
               && Objects.equals(this.departureDate, guestDetails.departureDate)
               && Objects.equals(this.guestLanguage, guestDetails.guestLanguage)
               && Objects.equals(this.guestId, guestDetails.guestId)
               && Objects.equals(this.reservationId, guestDetails.reservationId)
               && Objects.equals(this.emailId, guestDetails.emailId)
               && Objects.equals(this.phoneNumber, guestDetails.phoneNumber)
               && Objects.equals(this.groupCode, guestDetails.groupCode)
               && Objects.equals(this.uniqueId, guestDetails.uniqueId)
               && Objects.equals(this.guestType, guestDetails.guestType)
               && Objects.equals(this.welcomeMoodId,
                        guestDetails.welcomeMoodId);
   }

   @Override
   public int hashCode()
   {
      return Objects.hash(guestName, guestTitle, guestFirstName, guestLastName,
               guestFullName, roomNumber, remoteCheckout, safeFlag, revisitFlag,
               tvRights, videoRights, vipStatus, alternateName, incognitoName,
               arrivalDate, departureDate, guestLanguage, guestId,
               reservationId, emailId, phoneNumber, groupCode, uniqueId,
               guestType);
   }


   @Override
   public String toString()
   {
      StringBuilder sb = new StringBuilder();
      sb.append("class GuestDetails {\n");

      sb.append("    guestName: ").append(toIndentedString(guestName))
               .append("\n");
      sb.append("    guestTitle: ").append(toIndentedString(guestTitle))
               .append("\n");
      sb.append("    guestFirstName: ").append(toIndentedString(guestFirstName))
               .append("\n");
      sb.append("    guestLastName: ").append(toIndentedString(guestLastName))
               .append("\n");
      sb.append("    guestFullName: ").append(toIndentedString(guestFullName))
               .append("\n");
      sb.append("    roomNumber: ").append(toIndentedString(roomNumber))
               .append("\n");
      sb.append("    remoteCheckout: ").append(toIndentedString(remoteCheckout))
               .append("\n");
      sb.append("    safeFlag: ").append(toIndentedString(safeFlag))
               .append("\n");
      sb.append("    revisitFlag: ").append(toIndentedString(revisitFlag))
               .append("\n");
      sb.append("    tvRights: ").append(toIndentedString(tvRights))
               .append("\n");
      sb.append("    videoRights: ").append(toIndentedString(videoRights))
               .append("\n");
      sb.append("    vipStatus: ").append(toIndentedString(vipStatus))
               .append("\n");
      sb.append("    alternateName: ").append(toIndentedString(alternateName))
               .append("\n");
      sb.append("    incognitoName: ").append(toIndentedString(incognitoName))
               .append("\n");
      sb.append("    arrivalDate: ").append(toIndentedString(arrivalDate))
               .append("\n");
      sb.append("    departureDate: ").append(toIndentedString(departureDate))
               .append("\n");
      sb.append("    guestLanguage: ").append(toIndentedString(guestLanguage))
               .append("\n");
      sb.append("    guestId: ").append(toIndentedString(guestId)).append("\n");
      sb.append("    reservationId: ").append(toIndentedString(reservationId))
               .append("\n");
      sb.append("    emailId: ").append(toIndentedString(emailId)).append("\n");
      sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber))
               .append("\n");
      sb.append("    groupCode: ").append(toIndentedString(groupCode))
               .append("\n");
      sb.append("    uniqueId: ").append(toIndentedString(uniqueId))
               .append("\n");
      sb.append("    guestType: ").append(toIndentedString(guestType))
               .append("\n");
      sb.append("    welcomeMoodId: ").append(toIndentedString(welcomeMoodId))
               .append("\n");

      sb.append("}");
      return sb.toString();
   }

   /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
   private String toIndentedString(java.lang.Object o)
   {
      if (o == null)
      {
         return "null";
      }
      return o.toString().replace("\n", "\n    ");
   }
}

