/*
 * DigiValet PMS
 * This is DigiValet PMS application services for fetching room status, bill details, guest information, setting up wake up call etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * GuestData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-11-03T08:52:10.265Z")
public class GuestData   {
  @JsonProperty("status")
  private Boolean status = false;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("data")
  private List<GuestDetails> data = null;
  
  @JsonProperty("activeGuestId")
  private List<String> activeGuestId = null;
  

  @JsonProperty("response_tag")
  private Long responseTag = null;

  public GuestData status(Boolean status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(value = "")
  public Boolean getStatus() {
    return status;
  }

  public void setStatus(Boolean status) {
    this.status = status;
  }

  
  public GuestData message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   **/
  @JsonProperty("message")
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public GuestData data(List<GuestDetails> data) {
    this.data = data;
    return this;
  }

  public GuestData addDataItem(GuestDetails dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<GuestDetails>();
    }
    this.data.add(dataItem);
    return this;
  }

  public GuestData activeGuestId(List<String> activeGuestId) {
     this.activeGuestId = activeGuestId;
     return this;
   }

   public GuestData addActiveGuestIdItem(String activeGuestIdItem) {
     if (this.activeGuestId == null) {
       this.activeGuestId = new ArrayList<String>();
     }
     this.activeGuestId.add(activeGuestIdItem);
     return this;
   }

   /**
    * Get activeGuestId
    * @return activeGuestId
    **/
   @JsonProperty("activeGuestId")
   @ApiModelProperty(value = "")
   public List<String> getActiveGuestId() {
     return activeGuestId;
   }

   public void setActiveGuestId(List<String> activeGuestId) {
     this.activeGuestId = activeGuestId;
   }

  
  /**
   * Get data
   * @return data
   **/
  @JsonProperty("data")
  @ApiModelProperty(value = "")
  public List<GuestDetails> getData() {
    return data;
  }

  public void setData(List<GuestDetails> data) {
    this.data = data;
  }
  

  public GuestData responseTag(Long responseTag) {
    this.responseTag = responseTag;
    return this;
  }
  
  
  

  /**
   * Get responseTag
   * @return responseTag
   **/
  @JsonProperty("response_tag")
  @ApiModelProperty(value = "")
  public Long getResponseTag() {
    return responseTag;
  }

  public void setResponseTag(Long responseTag) {
    this.responseTag = responseTag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuestData guestData = (GuestData) o;
    return Objects.equals(this.status, guestData.status) &&
        Objects.equals(this.message, guestData.message) &&
        Objects.equals(this.data, guestData.data) &&
        Objects.equals(this.responseTag, guestData.responseTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, data, responseTag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuestData {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    responseTag: ").append(toIndentedString(responseTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

