/*
 * DigiValet-IDA
 * This is DigiValet Server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * Items
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-01-21T13:21:56.464Z")
public class Items   {
  @JsonProperty("conditional_column")
  private String conditionalColumn = null;

  @JsonProperty("conditional_operator")
  private String conditionalOperator = null;

  @JsonProperty("conditional_value")
  private String conditionalValue = null;

  public Items conditionalColumn(String conditionalColumn) {
    this.conditionalColumn = conditionalColumn;
    return this;
  }

  /**
   * Get conditionalColumn
   * @return conditionalColumn
   **/
  @JsonProperty("conditional_column")
  @ApiModelProperty(value = "")
  public String getConditionalColumn() {
    return conditionalColumn;
  }

  public void setConditionalColumn(String conditionalColumn) {
    this.conditionalColumn = conditionalColumn;
  }

  public Items conditionalOperator(String conditionalOperator) {
    this.conditionalOperator = conditionalOperator;
    return this;
  }

  /**
   * Get conditionalOperator
   * @return conditionalOperator
   **/
  @JsonProperty("conditional_operator")
  @ApiModelProperty(value = "")
  public String getConditionalOperator() {
    return conditionalOperator;
  }

  public void setConditionalOperator(String conditionalOperator) {
    this.conditionalOperator = conditionalOperator;
  }

  public Items conditionalValue(String conditionalValue) {
    this.conditionalValue = conditionalValue;
    return this;
  }

  /**
   * Get conditionalValue
   * @return conditionalValue
   **/
  @JsonProperty("conditional_value")
  @ApiModelProperty(value = "")
  public String getConditionalValue() {
    return conditionalValue;
  }

  public void setConditionalValue(String conditionalValue) {
    this.conditionalValue = conditionalValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Items items = (Items) o;
    return Objects.equals(this.conditionalColumn, items.conditionalColumn) &&
        Objects.equals(this.conditionalOperator, items.conditionalOperator) &&
        Objects.equals(this.conditionalValue, items.conditionalValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditionalColumn, conditionalOperator, conditionalValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Items {\n");
    
    sb.append("    conditionalColumn: ").append(toIndentedString(conditionalColumn)).append("\n");
    sb.append("    conditionalOperator: ").append(toIndentedString(conditionalOperator)).append("\n");
    sb.append("    conditionalValue: ").append(toIndentedString(conditionalValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

