/*
 * DigiValet PMS
 * This is DigiValet PMS application services for fetching room status, bill details, guest information, setting up wake up call etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.model;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * MovieDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-12-25T12:20:33.991Z")
public class MovieDetails   {
  @JsonProperty("details")
  private List<MovieData> details = null;

  @JsonProperty("dvcId")
  private String dvcId = null;

  @JsonProperty("inRoomDeviceId")
  private String inRoomDeviceId = null;

  public MovieDetails details(List<MovieData> details) {
    this.details = details;
    return this;
  }

  public MovieDetails addDetailsItem(MovieData detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<MovieData>();
    }
    this.details.add(detailsItem);
    return this;
  }

  /**
   * Get details
   * @return details
   **/
  @JsonProperty("details")
  @ApiModelProperty(value = "")
  public List<MovieData> getDetails() {
    return details;
  }

  public void setDetails(List<MovieData> details) {
    this.details = details;
  }

  public MovieDetails dvcId(String dvcId) {
    this.dvcId = dvcId;
    return this;
  }

  /**
   * Get dvcId
   * @return dvcId
   **/
  @JsonProperty("dvcId")
  @ApiModelProperty(value = "")
  public String getDvcId() {
    return dvcId;
  }

  public void setDvcId(String dvcId) {
    this.dvcId = dvcId;
  }

  public MovieDetails inRoomDeviceId(String inRoomDeviceId) {
    this.inRoomDeviceId = inRoomDeviceId;
    return this;
  }

  /**
   * Get inRoomDeviceId
   * @return inRoomDeviceId
   **/
  @JsonProperty("inRoomDeviceId")
  @ApiModelProperty(value = "")
  public String getInRoomDeviceId() {
    return inRoomDeviceId;
  }

  public void setInRoomDeviceId(String inRoomDeviceId) {
    this.inRoomDeviceId = inRoomDeviceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieDetails movieDetails = (MovieDetails) o;
    return Objects.equals(this.details, movieDetails.details) &&
        Objects.equals(this.dvcId, movieDetails.dvcId) &&
        Objects.equals(this.inRoomDeviceId, movieDetails.inRoomDeviceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, dvcId, inRoomDeviceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovieDetails {\n");
    
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    dvcId: ").append(toIndentedString(dvcId)).append("\n");
    sb.append("    inRoomDeviceId: ").append(toIndentedString(inRoomDeviceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

