/*
 * DigiValet PMS
 * This is DigiValet PMS application services for fetching room status, bill details, guest information, setting up wake up call etc.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.model;

import java.math.BigDecimal;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * MovieData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-12-25T12:20:33.991Z")
public class MovieData   {
  @JsonProperty("movieId")
  private String movieId = null;

  @JsonProperty("startTime")
  private Long startTime = null;

  @JsonProperty("endTime")
  private Long endTime = null;

  @JsonProperty("seek")
  private BigDecimal seek = null;

  @JsonProperty("audioId")
  private String audioId = null;

  @JsonProperty("subtitleId")
  private String subtitleId = null;

  @JsonProperty("duration")
  private String duration = null;

  @JsonProperty("dimension")
  private String dimension = null;

  @JsonProperty("alignment")
  private String alignment = null;

  @JsonProperty("isFinished")
  private Boolean isFinished = null;

  @JsonProperty("state")
  private String state = null;

  public MovieData movieId(String movieId) {
    this.movieId = movieId;
    return this;
  }

  /**
   * Get movieId
   * @return movieId
   **/
  @JsonProperty("movieId")
  @ApiModelProperty(value = "")
  public String getMovieId() {
    return movieId;
  }

  public void setMovieId(String movieId) {
    this.movieId = movieId;
  }

  public MovieData startTime(Long startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * Get startTime
   * @return startTime
   **/
  @JsonProperty("startTime")
  @ApiModelProperty(value = "")
  public Long getStartTime() {
    return startTime;
  }

  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }

  public MovieData endTime(Long endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * Get endTime
   * @return endTime
   **/
  @JsonProperty("endTime")
  @ApiModelProperty(value = "")
  public Long getEndTime() {
    return endTime;
  }

  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }

  public MovieData seek(BigDecimal seek) {
    this.seek = seek;
    return this;
  }

  /**
   * Get seek
   * @return seek
   **/
  @JsonProperty("seek")
  @ApiModelProperty(value = "")
  public BigDecimal getSeek() {
    return seek;
  }

  public void setSeek(BigDecimal seek) {
    this.seek = seek;
  }

  public MovieData audioId(String audioId) {
    this.audioId = audioId;
    return this;
  }

  /**
   * Get audioId
   * @return audioId
   **/
  @JsonProperty("audioId")
  @ApiModelProperty(value = "")
  public String getAudioId() {
    return audioId;
  }

  public void setAudioId(String audioId) {
    this.audioId = audioId;
  }

  public MovieData subtitleId(String subtitleId) {
    this.subtitleId = subtitleId;
    return this;
  }

  /**
   * Get subtitleId
   * @return subtitleId
   **/
  @JsonProperty("subtitleId")
  @ApiModelProperty(value = "")
  public String getSubtitleId() {
    return subtitleId;
  }

  public void setSubtitleId(String subtitleId) {
    this.subtitleId = subtitleId;
  }

  public MovieData duration(String duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Get duration
   * @return duration
   **/
  @JsonProperty("duration")
  @ApiModelProperty(value = "")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public MovieData dimension(String dimension) {
    this.dimension = dimension;
    return this;
  }

  /**
   * Get dimension
   * @return dimension
   **/
  @JsonProperty("dimension")
  @ApiModelProperty(value = "")
  public String getDimension() {
    return dimension;
  }

  public void setDimension(String dimension) {
    this.dimension = dimension;
  }

  public MovieData alignment(String alignment) {
    this.alignment = alignment;
    return this;
  }

  /**
   * Get alignment
   * @return alignment
   **/
  @JsonProperty("alignment")
  @ApiModelProperty(value = "")
  public String getAlignment() {
    return alignment;
  }

  public void setAlignment(String alignment) {
    this.alignment = alignment;
  }

  public MovieData isFinished(Boolean isFinished) {
    this.isFinished = isFinished;
    return this;
  }

  /**
   * Get isFinished
   * @return isFinished
   **/
  @JsonProperty("isFinished")
  @ApiModelProperty(value = "")
  public Boolean getIsFinished() {
    return isFinished;
  }

  public void setIsFinished(Boolean isFinished) {
    this.isFinished = isFinished;
  }

  public MovieData state(String state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   **/
  @JsonProperty("state")
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieData movieData = (MovieData) o;
    return Objects.equals(this.movieId, movieData.movieId) &&
        Objects.equals(this.startTime, movieData.startTime) &&
        Objects.equals(this.endTime, movieData.endTime) &&
        Objects.equals(this.seek, movieData.seek) &&
        Objects.equals(this.audioId, movieData.audioId) &&
        Objects.equals(this.subtitleId, movieData.subtitleId) &&
        Objects.equals(this.duration, movieData.duration) &&
        Objects.equals(this.dimension, movieData.dimension) &&
        Objects.equals(this.alignment, movieData.alignment) &&
        Objects.equals(this.isFinished, movieData.isFinished) &&
        Objects.equals(this.state, movieData.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(movieId, startTime, endTime, seek, audioId, subtitleId, duration, dimension, alignment, isFinished, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovieData {\n");
    
    sb.append("    movieId: ").append(toIndentedString(movieId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    seek: ").append(toIndentedString(seek)).append("\n");
    sb.append("    audioId: ").append(toIndentedString(audioId)).append("\n");
    sb.append("    subtitleId: ").append(toIndentedString(subtitleId)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    dimension: ").append(toIndentedString(dimension)).append("\n");
    sb.append("    alignment: ").append(toIndentedString(alignment)).append("\n");
    sb.append("    isFinished: ").append(toIndentedString(isFinished)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

