/*
 * Digivalet Services Status
 * This is DigiValet Service Status server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.serviceStatus.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;

/**
 * ModuleStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-08-27T07:13:54.980Z")
public class ModuleStatus   {
  @JsonProperty("moduleName")
  private String moduleName = null;

  @JsonProperty("vendorName")
  private String vendorName = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    GREEN("GREEN"),
    
    RED("RED"),
    
    AMBER("AMBER");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("lastSuccessTimestamp")
  private Long lastSuccessTimestamp = null;

  @JsonProperty("failedRequestCount")
  private Integer failedRequestCount = null;

  @JsonProperty("remarks")
  private String remarks = null;

  public ModuleStatus moduleName(String moduleName) {
    this.moduleName = moduleName;
    return this;
  }

  /**
   * Module name of the service
   * @return moduleName
   **/
  @JsonProperty("moduleName")
  @ApiModelProperty(example = "IRD", value = "Module name of the service")
  public String getModuleName() {
    return moduleName;
  }

  public void setModuleName(String moduleName) {
    this.moduleName = moduleName;
  }

  public ModuleStatus vendorName(String vendorName) {
    this.vendorName = vendorName;
    return this;
  }

  /**
   * Name of the Vendor for the module
   * @return vendorName
   **/
  @JsonProperty("vendorName")
  @ApiModelProperty(example = "OHEICS", value = "Name of the Vendor for the module")
  public String getVendorName() {
    return vendorName;
  }

  public void setVendorName(String vendorName) {
    this.vendorName = vendorName;
  }

  public ModuleStatus status(StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(example = "GREEN", value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public ModuleStatus lastSuccessTimestamp(Long lastSuccessTimestamp) {
    this.lastSuccessTimestamp = lastSuccessTimestamp;
    return this;
  }

  /**
   * The unix timestamp of the latest successful transaction.
   * @return lastSuccessTimestamp
   **/
  @JsonProperty("lastSuccessTimestamp")
  @ApiModelProperty(example = "1535191460000", value = "The unix timestamp of the latest successful transaction.")
  public Long getLastSuccessTimestamp() {
    return lastSuccessTimestamp;
  }

  public void setLastSuccessTimestamp(Long lastSuccessTimestamp) {
    this.lastSuccessTimestamp = lastSuccessTimestamp;
  }

  public ModuleStatus failedRequestCount(Integer failedRequestCount) {
    this.failedRequestCount = failedRequestCount;
    return this;
  }

  /**
   * The count will be -1, where it is not applicable.
   * @return failedRequestCount
   **/
  @JsonProperty("failedRequestCount")
  @ApiModelProperty(example = "2", value = "The count will be -1, where it is not applicable.")
  public Integer getFailedRequestCount() {
    return failedRequestCount;
  }

  public void setFailedRequestCount(Integer failedRequestCount) {
    this.failedRequestCount = failedRequestCount;
  }

  public ModuleStatus remarks(String remarks) {
    this.remarks = remarks;
    return this;
  }

  /**
   * Get remarks
   * @return remarks
   **/
  @JsonProperty("remarks")
  @ApiModelProperty(example = "Error while rewuest, 404 Not Found", value = "")
  public String getRemarks() {
    return remarks;
  }

  public void setRemarks(String remarks) {
    this.remarks = remarks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModuleStatus moduleStatus = (ModuleStatus) o;
    return Objects.equals(this.moduleName, moduleStatus.moduleName) &&
        Objects.equals(this.vendorName, moduleStatus.vendorName) &&
        Objects.equals(this.status, moduleStatus.status) &&
        Objects.equals(this.lastSuccessTimestamp, moduleStatus.lastSuccessTimestamp) &&
        Objects.equals(this.failedRequestCount, moduleStatus.failedRequestCount) &&
        Objects.equals(this.remarks, moduleStatus.remarks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(moduleName, vendorName, status, lastSuccessTimestamp, failedRequestCount, remarks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModuleStatus {\n");
    
    sb.append("    moduleName: ").append(toIndentedString(moduleName)).append("\n");
    sb.append("    vendorName: ").append(toIndentedString(vendorName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastSuccessTimestamp: ").append(toIndentedString(lastSuccessTimestamp)).append("\n");
    sb.append("    failedRequestCount: ").append(toIndentedString(failedRequestCount)).append("\n");
    sb.append("    remarks: ").append(toIndentedString(remarks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

