/*
 * Digivalet Services Status
 * This is DigiValet Service Status server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@digivalet.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.digivalet.pmsi.serviceStatus.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets StatusEnum
 */
public enum StatusEnum {
  
  GREEN("GREEN"),
  
  RED("RED"),
  
  AMBER("AMBER");

  private String value;

  StatusEnum(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static StatusEnum fromValue(String text) {
    for (StatusEnum b : StatusEnum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

